- packages/components/src/form/Radio/Radio.js
- packages/components/src/form/Radio/Radio.styles.js
- packages/components/src/overlay/Drawer/Drawer.js
- packages/components/src/overlay/Drawer/Drawer.styles.js
- packages/leemons/src/scores/AttendanceControl/AttendanceControl.constants.js
- packages/leemons/src/scores/AttendanceControl/AttendanceControl.js
- packages/leemons/src/scores/AttendanceControl/AttendanceControl.mdx
- packages/leemons/src/scores/AttendanceControl/AttendanceControl.stories.js
- packages/leemons/src/scores/AttendanceControl/AttendanceControl.styles.js
- packages/leemons/src/scores/AttendanceControl/index.js
- packages/leemons/src/scores/AttendanceControl/mock/data.js
- packages/leemons/src/scores/AttendanceControlDrawer/AttendanceControlDrawer.constants.js
- packages/leemons/src/scores/AttendanceControlDrawer/AttendanceControlDrawer.js
- packages/leemons/src/scores/AttendanceControlDrawer/AttendanceControlDrawer.mdx
- packages/leemons/src/scores/AttendanceControlDrawer/AttendanceControlDrawer.stories.js
- packages/leemons/src/scores/AttendanceControlDrawer/AttendanceControlDrawer.styles.js
- packages/leemons/src/scores/AttendanceControlDrawer/index.js
- packages/leemons/src/scores/index.js
AttendanceControl component, some changes in Radio and Drawer styles
> (LMVP-225) - AttendanceControl

- packages/components/src/informative/Avatar/Avatar.constants.js
- packages/components/src/informative/Avatar/Avatar.js
- packages/components/src/informative/Avatar/Avatar.stories.js
- packages/components/src/informative/Avatar/Avatar.styles.js
- packages/components/src/informative/ChatMessage/ChatMessage.constants.js
- packages/components/src/informative/ChatMessage/ChatMessage.js
- packages/components/src/informative/ChatMessage/ChatMessage.mdx
- packages/components/src/informative/ChatMessage/ChatMessage.stories.js
- packages/components/src/informative/ChatMessage/ChatMessage.styles.js
- packages/components/src/informative/ChatMessage/index.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.stories.js
Added activity state to Avatar and UserDisplayItem, ChatMessage component
> (LMVP-226) - ChatMessage

- packages/components/src/form/ColorInput/ColorInput.js
Add clearable option to the ColorInput component for it to show a remove color button.
> fix(ColorInput): Add clearable option to the ColorInput component

- packages/components/src/form/DatePicker/DatePicker.js
Allow free input and placeHolder with the locale date format
> Añadir posibilidad de escribir la fecha en el DatePicker

- packages/components/src/informative/FileItemDisplay/FileItemDisplay.styles.js
- packages/components/src/tokens.compiled.js
- Fix with overflow-wrap: anywhere
> Task - Paso entregables - el componente de file upload no tiene ancho máximo y desborda

- packages/components/src/form/TableInput/TableInput.constants.js
- packages/components/src/form/TableInput/TableInput.js
- packages/components/src/form/TableInput/TableInput.stories.js
- packages/components/src/form/TableInput/TableInput.styles.js
- packages/components/src/form/TableInput/TableInputDisplay.js
feat(TableInputDisplay): add Actions label and isOneInput mode
> Task Creation - Evaluation step

- packages/leemons/src/common/HeaderDropdown/HeaderDropdown.js
- packages/leemons/src/common/HeaderDropdown/HeaderDropdown.styles.js
fix(HeaderDropdown): Fix Popover padding and if is only one Item, do not show chevron button.
> Program - Subject Nav - desplegable no es el correcto de dropdown

- packages/components/src/form/DropdownButton/DropdownButton.js
- packages/components/src/layout/TotalLayout/TotalLayoutFooter.js
- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.constants.js
- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.styles.js
- packages/components/src/layout/TotalLayout/TotalLayoutStepContainer/TotalLayoutStepContainer.js
- packages/components/src/layout/TotalLayout/TotalLayoutStepContainer/TotalLayoutStepContainer.styles.js
- packages/components/src/layout/TotalLayout/index.js
- packages/components/src/overlay/BaseDrawer/BaseDrawer.js
- packages/components/src/overlay/BaseDrawer/BaseDrawer.mdx
- packages/components/src/overlay/BaseDrawer/BaseDrawer.stories.js
- packages/components/src/overlay/BaseDrawer/BaseDrawer.styles.js
- packages/components/src/overlay/BaseDrawer/index.js
- packages/components/src/overlay/Drawer/Drawer.js
- packages/components/src/overlay/Drawer/components/DrawerContent.js
- packages/components/src/overlay/Drawer/components/DrawerFooter.js
- packages/components/src/overlay/Drawer/components/DrawerHeader.js
- packages/components/src/overlay/index.js
- Implement structured sections (Header, Content, Footer) in Drawer component for better organization and flexibility.
- Introduce `DrawerHeader`, `DrawerContent`, and `DrawerFooter` components for structured content management.
- Adjust Drawer styles and props to support new structured components.
- Update Drawer stories to demonstrate new features and usage.
- Refactor imports and exports across components for consistency and clarity.
BREAKING CHANGE: Changes to Drawer component structure and props may require updates in existing usage to accommodate new pattern.
> refactor(Drawer): enhance Drawer component with structured sections

- packages/components/src/layout/TLayout/TLayout.constants.js
- packages/components/src/layout/TLayout/TLayout.js
- packages/components/src/layout/TLayout/TLayout.stories.js
- packages/components/src/layout/TLayout/components/TLayoutContent.js
- packages/components/src/layout/TLayout/components/TLayoutFooter.js
- packages/components/src/layout/TLayout/components/TLayoutHeader.js
- packages/components/src/layout/TLayout/index.js
- packages/components/src/layout/TotalLayout/TotalLayoutFooterContainer/TotalLayoutFooterContainer.styles.js
- packages/components/src/layout/TotalLayout/TotalLayoutStepContainer/TotalLayoutStepContainer.styles.js
- packages/components/src/layout/index.js
- packages/components/src/overlay/Drawer/Drawer.styles.js
As abstraction over `TotalLayout` as composable components
> feat(Layout): Added `TLayout` component

- packages/components/src/informative/ChatMessage/ChatMessage.js
- packages/components/src/informative/ChatMessage/ChatMessage.styles.js
Ticket: [Notion](https://www.notion.so/leemons/Leemons-Product-Kanban-v2-0-b49859e964e145edb4e22caddb4571f7?p=b02da2c1564c456386bff42889ea43cf&pm=s)
> Bug: Ajustes refactor Comunica v3

- packages/components/src/overlay/ModalZoom/ModalZoom.js
fix(ModaZoom): add stopPropagation to zoom buttons
> Image asset player - ampliar y alejar de una foto

- packages/components/src/form/ColorInput/ColorInput.js
- packages/components/src/informative/Table/Table.js
- packages/components/src/informative/Table/Table.styles.js
feat(Table): add new prop to Table component to draw rows like LibraryCardAsset aspect
> New Asset Players - Nivel 2, 2.5 - C.Creator & assignment execution Vol.2

- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.js
- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.styles.js
fix(TotalLayoutHeader): add TextClamp to title and width control
> Nombre asset header - Controlar extensión

- packages/components/src/layout/VerticalStepperContainer/VerticalStepperContainer.styles.js
fix(components): align media queries to prevent footer problem on TL
> Solapamiento botón del footer con el botón de comunica

- packages/components/src/form/ListInput/ListInput.stories.js
- packages/components/src/form/ListInput/components/ListItem.js
- packages/components/src/form/ListInput/components/ListItem.styles.js
refactor(ListItem): 
- Change buttons and position of buttons on edit mode. 
- Add labels to that buttons. 
- Add focus on Input when user click on edit action. 
- Can call "update" function pressing "Enter" key.
> QBank - Creation - Ajustes

- packages/components/src/helpers/getUserFullName.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.js
fix(components): UserDisplayItem. Add comma between surname and name.
fix(components): getUserFullName  helper refactor.
> Unificar posición de Nombre y Apellidos y controlar espaciados

- packages/leemons/src/calendar/CalendarSubNavFilters/CalendarSubNavFilters.js
Add TextClamp to one line in  label Switch on Calendar SubNavFilters
> Transversal - Control de alias de Aula (grupo de alumnos) en varios frontales y cursos para programas tipo MOOC - Intento 2

- packages/components/src/form/TagsInput/TagsInput.js
add new feature: User can type some tags separated with commas. After press enter button, dropdown hide and user can see new tags (badges)
> Tags creation - Que se puedan meter separadas por comas y darle al enter

- packages/calendars/src/BigCalendar/components/AgentView/AgentView.js
fix(calendar): fix toolbar select on Agenda view.
> Selector de vista (dropdown) de la Agenda del dashboard y de Calendario

- packages/calendars/CHANGELOG.md
- packages/calendars/package.json
- packages/calendars/src/BigCalendar/components/AgentView/AgentView.js
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/form/TagsInput/TagsInput.js
- packages/components/src/overlay/Modal/Modal.js
- packages/components/src/overlay/Modal/Modal.styles.js
- packages/editors/CHANGELOG.md
- packages/editors/package.json
- packages/extras/CHANGELOG.md
- packages/extras/package.json
- packages/icons/CHANGELOG.md
- packages/icons/package.json
- packages/leemons/CHANGELOG.md
- packages/leemons/package.json
- packages/leemons/src/calendar/CalendarSubNavFilters/CalendarSubNavFilters.js
- packages/notifications/CHANGELOG.md
- packages/notifications/package.json
- **chore: version bump**
- **fix(leemons): add TextClamp to Switch labels in `CalendaSubNavFilters`**
- **feat(components): TagsInput - add multiple tags separated by commas**
- **fix(calendar): fix toolbar select on Agenda view.**
- **chore: version bump**
- **feat(modal): Added `padding` prop to change the padding around the modal**
- **chore: version bump**
> Release 1.3.0

- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.constants.js
- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.js
feat(components): Add rightZone prop to TotalLayoutHeader component
> feat(components): Add rightZone prop to TotalLayoutHeader component

- packages/editors/src/form/TextEditorInput/TextEditorInput.constants.js
- packages/editors/src/form/TextEditorInput/TextEditorInput.js
- packages/editors/src/form/TextEditorInput/TextEditorInput.stories.js
feat(editors): TexEditorInput new boolean prop: showToolbarHeading
> WYSIWYG Erróneo en Question Banks

- packages/components/src/informative/Avatar/Avatar.constants.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.styles.js
- Adjusted `AVATAR_SIZES` in `Avatar.constants.js` to include 'xmd' size.
- Modified `USER_DISPLAY_ITEM_SIZES` in `UserDisplayItem.js` to include 'xmd', 'lg'.
> Update Avatar and UserDisplayItem constants for improved size options

- packages/components/src/form/FileUpload/FileUpload.js
- packages/components/src/form/FileUpload/FileUpload.styles.js
refactor(components): Hide Upload button in `FileUpload` if single file and file already picked
> feat(components): Added `hideDropzone` prop to `FileUpload`

- packages/components/src/feedback/Alert/Alert.js
- packages/components/src/feedback/Alert/Alert.styles.js
This PR introduces several enhancements to the dashboard functionality for Admins
> New Dashboard for Admins

- packages/components/src/informative/Chip/Chip.constants.js
- packages/components/src/informative/Chip/Chip.js
- packages/components/src/informative/Chip/Chip.stories.js
- packages/components/src/informative/ChipsContainer/ChipsContainer.constants.js
- packages/components/src/informative/ChipsContainer/ChipsContainer.js
feat(Chips): 
- add two new props to truncate to n lines the chip text content:
- truncate: boolean
- truncateLines: number
> Sesiones: Minimovidas de UX/UI

- packages/components/src/misc/AvatarSubject/AvatarSubject.js
fix(AvatarSubject): Change 2 px for inititals font size and text size on xxlg
> Comportamientos a corregir de Avatar de asignatura en varios plugins

- packages/components/src/helpers/getUserFullName.js
The previous implementation was not trimming individual results and was
developed without following the linter rules, this PR fixes that.
> refactor(components): getUserFullName now trims the fullName

- packages/leemons/src/common/HeaderDropdown/HeaderDropdown.js
fix(leemons): HeaderDropdown. Add accessibility by keyboard to navigate between Popover.Dropdown elements.
> fix(leemons): add better accessibility to HeaderDropdown

- packages/components/src/form/DropdownButton/DropdownButton.constants.js
- packages/components/src/form/DropdownButton/DropdownButton.js
- packages/components/src/overlay/Dropdown/Item/Item.js
style(components): DropdownButton. Set default position and handle dropdown width (max and min)
feat(components): Dropdown Item. Add TextClamp (one line) to Item label.
> fix(components): set `DropdownButton` default position and limit sizes

- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.constants.js
- packages/components/src/layout/TotalLayout/TotalLayoutHeader/TotalLayoutHeader.js
feat(components): Add new prop to handle show icon or not (noIcon prop: boolean) on TotalLayoutHeader.
> feat(components): add new prop to hide icon in `TotalLayoutHeader`

- packages/components/src/form/DropdownButton/DropdownButton.js
fix(components): button property "textAling" is missing one "p" on value.
> fix(components): button property "textAlign" is missing one "p" on value

- packages/components/src/form/IconButton/IconButton.js
- packages/components/src/navigation/Tabs/TabNavList/Dropdown.js
- packages/components/src/navigation/Tabs/TabNavList/Dropdown.styles.js
- packages/components/src/navigation/Tabs/hooks/useVisibleRange.js
fix(components): Tabs. Update Menu component to v5 syntax. Adjust useVisibleRange hook and style Dropdown button.
fix(components): IconButton. Add cx to merge static and dynamic classNames
> fix(components): update Tabs Menu to v5 syntax and tweak useVisibleRange

- packages/components/src/form/Select/Select.constants.js
fix(components): Add searchable default prop to "true" on Select component.
> feat(components): make all selects searchable by default

- packages/components/src/helpers/getUserFullName.js
- packages/components/src/informative/AvatarsGroup/AvatarsGroup.js
- packages/components/src/informative/UserDisplayItem/UserDisplayItem.js
fix(components): add new property to getUserFullName to handle users with two surnames. Refactor on AvatarsGroup and UserDisplayItem
> fix(components): enhance user name handling for multiple surnames
